INSERT INTO release_notes (
  app_id,
  app_version,
  locale,
  schema_version,
  resource_version,
  current_title,
  current_body,
  upcoming_title,
  upcoming_body,
  status,
  updated_at
) VALUES
  (
    'autonotice',
    '0.1.0',
    'zh-Hans',
    1,
    '2026.07.21.1',
    '当前版本',
    '0.1 是 AutoNotice 的内部 Notice Engine 验证版本，未公开发布；它完成了位置选择、降水规则、Worker 定时判断与 APNs 投递的初始天气提醒闭环。',
    '后续计划',
    '0.2 已作为 AutoNotice 的首个公开版本在 App Store 上架，新增多类天气提醒、到期提醒、Developer Webhook Basic 和统一通知历史。',
    'published',
    '2026-07-21T13:50:00.000Z'
  ),
  (
    'autonotice',
    '0.1.0',
    'en',
    1,
    '2026.07.21.1',
    'Current Version',
    '0.1 is an internal Notice Engine validation build that was not publicly released. It established the first Weather Notice loop across location selection, precipitation rules, scheduled Worker evaluation, and APNs delivery.',
    'Coming Next',
    '0.2 is now the first public AutoNotice release on the App Store, adding multiple weather notices, Expiry Notice, Developer Webhook Basic, and unified notification history.',
    'published',
    '2026-07-21T13:50:00.000Z'
  ),
  (
    'autonotice',
    '0.2.0',
    'zh-Hans',
    1,
    '2026.07.21.1',
    '当前版本',
    '0.2 是 AutoNotice 的首个公开版本，已在 App Store 上架，包含天气提醒、到期提醒、Developer Webhook Basic、统一通知历史与稳定投递。',
    '后续计划',
    '0.3 聚焦全球英语市场基础、Webhook 独立入口与引导、凭据轮换和撤销、投递诊断，以及 APNs 恢复与弱网可靠性；通过真机和生产验收后再进入候选发布。',
    'published',
    '2026-07-21T13:50:00.000Z'
  ),
  (
    'autonotice',
    '0.2.0',
    'en',
    1,
    '2026.07.21.1',
    'Current Version',
    '0.2 is the first public AutoNotice release on the App Store, with Weather Notice, Expiry Notice, Developer Webhook Basic, unified notification history, and reliable delivery.',
    'Coming Next',
    '0.3 focuses on the global English-market foundation, a dedicated Webhook entry and onboarding, credential rotation and revocation, delivery diagnostics, APNs recovery, and weak-network reliability. A release candidate will follow real-device and production validation.',
    'published',
    '2026-07-21T13:50:00.000Z'
  ),
  (
    'autonotice',
    '0.3.0',
    'zh-Hans',
    1,
    '2026.07.21.1',
    '当前版本',
    '0.3 是当前开发版本：Webhook 已升级为可发现的独立入口，加入分步引导、凭据轮换与撤销、最近投递诊断；通知侧补充 APNs 就绪与恢复状态，以及有界网络重试。',
    '后续计划',
    '接下来完成真实弱网与前后台切换、production APNs、真实 Webhook、五个英语市场材料和真机验收；这些门禁通过后再创建候选构建，0.4 才进入 Module Platform 与 Notice Feedback。',
    'published',
    '2026-07-21T13:50:00.000Z'
  ),
  (
    'autonotice',
    '0.3.0',
    'en',
    1,
    '2026.07.21.1',
    'Current Version',
    '0.3 is the current development release. Webhook is now a discoverable product entry with guided setup, credential rotation and revocation, and recent-delivery diagnostics. Notification reliability adds APNs readiness and recovery states plus bounded network retries.',
    'Coming Next',
    'Next we will validate real weak-network and background transitions, production APNs, live Webhook delivery, five English-market storefronts, and real devices. Only after those gates will we create a release candidate; Module Platform and Notice Feedback remain in 0.4.',
    'published',
    '2026-07-21T13:50:00.000Z'
  )
ON CONFLICT(app_id, app_version, locale) DO UPDATE SET
  schema_version = excluded.schema_version,
  resource_version = excluded.resource_version,
  current_title = excluded.current_title,
  current_body = excluded.current_body,
  upcoming_title = excluded.upcoming_title,
  upcoming_body = excluded.upcoming_body,
  status = excluded.status,
  updated_at = excluded.updated_at;
