INSERT INTO release_notes (
  app_id,
  app_version,
  locale,
  schema_version,
  resource_version,
  current_title,
  current_body,
  upcoming_title,
  upcoming_body,
  status,
  updated_at
) VALUES
  (
    'autoledger',
    '1.5.0',
    'zh-Hans',
    1,
    '2026.07.06.2',
    '当前版本',
    '这个版本加入了 AutoLedger Pro 的第一批自动化能力：邮箱水单、专属收件箱、批量候选和重复账单提醒都会先进入待确认，确认后再入账。日常记账、截图识别、手动导入酒店水单、多账本和历史数据编辑仍可免费使用。',
    '后续计划',
    '接下来会继续打磨 Pro 订阅体验和酒店水单流程，让开通、恢复购买、收件箱候选和确认入账更顺手。后续版本会加入更强的搜索、订阅异常提醒、月结导出和自动规则整理。',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.5.0',
    'zh-Hant',
    1,
    '2026.07.06.2',
    '目前版本',
    '這個版本加入了 AutoLedger Pro 的第一批自動化能力：郵件水單、專屬收件箱、批次候選和重複帳單提醒都會先進入待確認，確認後再入帳。日常記帳、截圖辨識、手動匯入飯店水單、多帳本和歷史資料編輯仍可免費使用。',
    '後續計畫',
    '接下來會繼續打磨 Pro 訂閱體驗和飯店水單流程，讓開通、恢復購買、收件箱候選和確認入帳更順手。後續版本會加入更強的搜尋、訂閱異常提醒、月結匯出和自動規則整理。',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.5.0',
    'en',
    1,
    '2026.07.06.2',
    'Current Version',
    'This version adds the first AutoLedger Pro automations: email folios, a dedicated folio inbox, batch candidates, and duplicate alerts all go to review first, then save only after you confirm. Everyday bookkeeping, screenshot recognition, manual hotel PDF import, multiple ledgers, and editing history remain free.',
    'Coming Next',
    'Next we will keep polishing the Pro subscription experience and hotel folio workflow, so subscribing, restoring purchases, reviewing inbox candidates, and saving confirmed records feel smoother. Later releases will add stronger search, subscription anomaly alerts, month-end exports, and smarter rules automation.',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.5.0',
    'ja',
    1,
    '2026.07.06.2',
    '現在のバージョン',
    'このバージョンでは、AutoLedger Pro の最初の自動化を追加しました。メール明細、専用受信箱、一括候補、重複の確認はまずレビューに入り、確認してから保存されます。日常の記帳、スクリーンショット認識、手動ホテル PDF 取り込み、複数台帳、履歴編集は引き続き無料で使えます。',
    '次に予定',
    '次は Pro のサブスクリプション体験とホテル明細フローをさらに磨きます。登録、購入の復元、受信箱の候補確認、確認後の保存をより使いやすくし、その後は検索、サブスクリプション異常通知、月末エクスポート、自動ルール整理を強化します。',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.5.0',
    'ko',
    1,
    '2026.07.06.2',
    '현재 버전',
    '이 버전에는 첫 번째 AutoLedger Pro 자동화가 추가되었습니다. 전자 메일 Folio, 전용 Folio 받은 편지함, 일괄 후보 및 중복 경고가 모두 먼저 검토된 다음 확인한 후에만 저장됩니다. 일상 부기, 스크린샷 인식, 수동 호텔 PDF 가져오기, 다중 원장, 편집 내역은 무료로 유지됩니다.',
    '다음 계획',
    '다음으로 Pro 구독 경험과 호텔 폴리오 작업 흐름을 계속 개선하여 구독, 구매 복원, 받은 편지함 후보 검토, 확인된 기록 저장을 더 원활하게 만들겠습니다. 이후 릴리스에는 더 강력한 검색, 구독 이상 경고, 월말 내보내기 및 더 스마트한 규칙 자동화가 추가됩니다.',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'zh-Hans',
    1,
    '2026.07.06.2',
    '当前版本',
    '这个版本让记账更适合真实票据场景：票据扫描升级为实时 OCR，不支持时自动回退拍照或相册；新增韩语界面和韩语账单识别；语言与区域里可设置 App 语言和默认消费币种；酒店水单复核支持更清晰的解析进度、房号、灵活日期、拒绝后重新导入，并按你确认后的日期、房晚和币种入账。',
    '后续计划',
    '接下来会继续补齐更多地区票据样本，完善多币种换算、酒店历史天气和订阅状态同步，并推进 Pro 自动化里的搜索、月结导出和规则整理。',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'zh-Hant',
    1,
    '2026.07.06.2',
    '目前版本',
    '這個版本讓記帳更適合真實票據場景：票據掃描升級為即時 OCR，不支援時會自動回退到拍照或相簿；新增韓語介面和韓語帳單辨識；語言與地區可設定 App 語言和預設消費幣別；飯店水單複核支援更清楚的解析進度、房號、彈性日期、拒絕後重新匯入，並依你確認後的日期、房晚和幣別入帳。',
    '後續計畫',
    '接下來會繼續補齊更多地區票據樣本，完善多幣別換算、飯店歷史天氣和訂閱狀態同步，並推進 Pro 自動化中的搜尋、月結匯出和規則整理。',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'en',
    1,
    '2026.07.06.2',
    'Current Version',
    'This version makes AutoLedger better for real receipt workflows: receipt scanning now starts with live OCR and falls back to camera or photos when needed. Korean UI and Korean receipt recognition are added. Language & Region now includes app language and default spending currency. Hotel folio review has clearer parsing progress, room numbers, flexible dates, reimport after rejection, and saves the dates, nights, currency, and amount you confirm.',
    'Coming Next',
    'Next we will add more regional receipt samples, refine multi-currency conversion, hotel history context, and subscription status sync, and continue Pro automations for search, month-end exports, and rules.',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'ja',
    1,
    '2026.07.06.2',
    '現在のバージョン',
    'このバージョンでは、実際のレシート作業に合わせて使いやすくしました。レシートスキャンはリアルタイム OCR から始まり、必要に応じてカメラ撮影や写真選択に戻れます。韓国語 UI と韓国語レシート認識を追加し、「言語と地域」で App の言語と既定の支出通貨を設定できます。ホテル明細の確認では、解析進行、部屋番号、柔軟な日付、拒否後の再取り込みに対応し、確認した日付、泊数、通貨、金額で保存します。',
    '次に予定',
    '次は地域別のレシートサンプルを増やし、多通貨換算、ホテル履歴の文脈、サブスクリプション状態同期を磨き、検索、月末エクスポート、ルール整理などの Pro 自動化を進めます。',
    'published',
    '2026-07-06T04:45:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'ko',
    1,
    '2026.07.06.2',
    '현재 버전',
    '이번 버전은 실제 영수증 작업에 더 잘 맞도록 다듬었습니다. 영수증 스캔은 실시간 OCR로 시작하고, 필요할 때 카메라 촬영이나 사진 선택으로 돌아갑니다. 한국어 UI와 한국어 영수증 인식을 추가했으며, 언어 및 지역에서 App 언어와 기본 지출 통화를 설정할 수 있습니다. 호텔 Folio 검토는 더 명확한 분석 진행, 객실 번호, 유연한 날짜, 거절 후 다시 가져오기를 지원하고, 확인한 날짜, 숙박일수, 통화, 금액으로 저장합니다.',
    '다음 계획',
    '다음에는 더 많은 지역 영수증 샘플을 보강하고, 다중 통화 환산, 호텔 기록 맥락, 구독 상태 동기화를 개선하며, 검색, 월말 내보내기, 규칙 정리 같은 Pro 자동화를 계속 진행합니다.',
    'published',
    '2026-07-06T04:45:00.000Z'
  )
ON CONFLICT(app_id, app_version, locale) DO UPDATE SET
  schema_version = excluded.schema_version,
  resource_version = excluded.resource_version,
  current_title = excluded.current_title,
  current_body = excluded.current_body,
  upcoming_title = excluded.upcoming_title,
  upcoming_body = excluded.upcoming_body,
  status = excluded.status,
  updated_at = excluded.updated_at;
