INSERT INTO release_notes (
  app_id,
  app_version,
  locale,
  schema_version,
  resource_version,
  current_title,
  current_body,
  upcoming_title,
  upcoming_body,
  status,
  updated_at
) VALUES
  (
    'autoledger',
    '1.6.0',
    'zh-Hans',
    1,
    '2026.07.06.1',
    '当前版本',
    '这个版本加入了 AutoLedger Pro 的第一批自动化能力：邮箱水单、专属收件箱、批量候选和重复账单提醒都会先进入待确认，确认后再入账。日常记账、截图识别、手动导入酒店水单、多账本和历史数据编辑仍可免费使用。',
    '后续计划',
    '接下来会继续打磨 Pro 订阅体验和酒店水单流程，让开通、恢复购买、收件箱候选和确认入账更顺手。后续版本会加入更强的搜索、订阅异常提醒、月结导出和自动规则整理。',
    'published',
    '2026-07-06T00:00:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'zh-Hant',
    1,
    '2026.07.06.1',
    '目前版本',
    '這個版本加入了 AutoLedger Pro 的第一批自動化能力：郵件水單、專屬收件箱、批次候選和重複帳單提醒都會先進入待確認，確認後再入帳。日常記帳、截圖辨識、手動匯入飯店水單、多帳本和歷史資料編輯仍可免費使用。',
    '後續計畫',
    '接下來會繼續打磨 Pro 訂閱體驗和飯店水單流程，讓開通、恢復購買、收件箱候選和確認入帳更順手。後續版本會加入更強的搜尋、訂閱異常提醒、月結匯出和自動規則整理。',
    'published',
    '2026-07-06T00:00:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'en',
    1,
    '2026.07.06.1',
    'Current Version',
    'This version adds the first AutoLedger Pro automations: email folios, a dedicated folio inbox, batch candidates, and duplicate alerts all go to review first, then save only after you confirm. Everyday bookkeeping, screenshot recognition, manual hotel PDF import, multiple ledgers, and editing history remain free.',
    'Coming Next',
    'Next we will keep polishing the Pro subscription experience and hotel folio workflow, so subscribing, restoring purchases, reviewing inbox candidates, and saving confirmed records feel smoother. Later releases will add stronger search, subscription anomaly alerts, month-end exports, and smarter rules automation.',
    'published',
    '2026-07-06T00:00:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'ja',
    1,
    '2026.07.06.1',
    '現在のバージョン',
    'このバージョンでは、AutoLedger Pro の最初の自動化を追加しました。メール明細、専用受信箱、一括候補、重複の確認はまずレビューに入り、確認してから保存されます。日常の記帳、スクリーンショット認識、手動ホテル PDF 取り込み、複数台帳、履歴編集は引き続き無料で使えます。',
    '次に予定',
    '次は Pro のサブスクリプション体験とホテル明細フローをさらに磨きます。登録、購入の復元、受信箱の候補確認、確認後の保存をより使いやすくし、その後は検索、サブスクリプション異常通知、月末エクスポート、自動ルール整理を強化します。',
    'published',
    '2026-07-06T00:00:00.000Z'
  ),
  (
    'autoledger',
    '1.6.0',
    'ko',
    1,
    '2026.07.06.1',
    '현재 버전',
    '이 버전에는 첫 번째 AutoLedger Pro 자동화가 추가되었습니다. 전자 메일 Folio, 전용 Folio 받은 편지함, 일괄 후보 및 중복 경고가 모두 먼저 검토된 다음 확인한 후에만 저장됩니다. 일상 부기, 스크린샷 인식, 수동 호텔 PDF 가져오기, 다중 원장, 편집 내역은 무료로 유지됩니다.',
    '다음 계획',
    '다음으로 Pro 구독 경험과 호텔 폴리오 작업 흐름을 계속 개선하여 구독, 구매 복원, 받은 편지함 후보 검토, 확인된 기록 저장을 더 원활하게 만들겠습니다. 이후 릴리스에는 더 강력한 검색, 구독 이상 경고, 월말 내보내기 및 더 스마트한 규칙 자동화가 추가됩니다.',
    'published',
    '2026-07-06T00:00:00.000Z'
  )
ON CONFLICT(app_id, app_version, locale) DO UPDATE SET
  schema_version = excluded.schema_version,
  resource_version = excluded.resource_version,
  current_title = excluded.current_title,
  current_body = excluded.current_body,
  upcoming_title = excluded.upcoming_title,
  upcoming_body = excluded.upcoming_body,
  status = excluded.status,
  updated_at = excluded.updated_at;
